"""
Markdown report generator for XSSForge.

Generates GitHub-friendly Markdown reports.
"""

from datetime import datetime
from pathlib import Path

from xssforge.detectors.reflected import XSSFinding


class MarkdownReporter:
    """Generates Markdown reports for XSS findings."""

    def __init__(self, findings: list[XSSFinding]):
        self.findings = findings
        self.target = ""
        self.scan_time = 0.0

    def set_metadata(self, target: str = "", scan_time: float = 0.0):
        """Set report metadata."""
        self.target = target
        self.scan_time = scan_time

    def generate(self) -> str:
        """Generate the Markdown report."""
        lines = []

        # Header
        lines.append("# XSSForge Security Report")
        lines.append("")
        lines.append(f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}")
        lines.append(f"**Target:** {self.target or 'Multiple targets'}")
        lines.append(f"**Scan Duration:** {self.scan_time:.2f} seconds")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")

        severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
        type_counts = {"reflected": 0, "stored": 0, "dom": 0}

        for finding in self.findings:
            severity = finding.severity.lower()
            if severity in severity_counts:
                severity_counts[severity] += 1
            xss_type = finding.xss_type.lower()
            if xss_type in type_counts:
                type_counts[xss_type] += 1

        for severity, count in severity_counts.items():
            emoji = self._severity_emoji(severity)
            lines.append(f"| {emoji} {severity.capitalize()} | {count} |")

        lines.append("")
        lines.append(f"**Total Vulnerabilities:** {len(self.findings)}")
        lines.append("")

        # Findings by type
        lines.append("### By Type")
        lines.append("")
        lines.append(f"- Reflected XSS: {type_counts['reflected']}")
        lines.append(f"- Stored XSS: {type_counts['stored']}")
        lines.append(f"- DOM XSS: {type_counts['dom']}")
        lines.append("")

        # Detailed findings
        lines.append("## Findings")
        lines.append("")

        for i, finding in enumerate(self.findings, 1):
            lines.extend(self._render_finding(finding, i))
            lines.append("")

        # Remediation summary
        lines.append("## Remediation Recommendations")
        lines.append("")
        lines.append("### General XSS Prevention")
        lines.append("")
        lines.append("1. **Input Validation**: Validate and sanitize all user input")
        lines.append("2. **Output Encoding**: Encode output based on context (HTML, JavaScript, URL)")
        lines.append("3. **Content Security Policy**: Implement strict CSP headers")
        lines.append("4. **HTTPOnly Cookies**: Set HttpOnly flag on session cookies")
        lines.append("5. **Use Security Libraries**: Use trusted sanitization libraries like DOMPurify")
        lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by [XSSForge](https://github.com/xssforge/xssforge) v1.0.0*")

        return "\n".join(lines)

    def _render_finding(self, finding: XSSFinding, index: int) -> list[str]:
        """Render a single finding to Markdown."""
        lines = []

        severity_emoji = self._severity_emoji(finding.severity)
        type_emoji = self._type_emoji(finding.xss_type)

        lines.append(f"### {severity_emoji} Finding #{index}: {finding.xss_type.upper()} XSS")
        lines.append("")
        lines.append(f"**Severity:** {finding.severity.upper()}")
        lines.append(f"**Type:** {type_emoji} {finding.xss_type}")
        lines.append(f"**Confidence:** {int(finding.confidence * 100)}%")
        lines.append("")

        lines.append("#### Details")
        lines.append("")
        lines.append(f"- **URL:** `{finding.url}`")
        lines.append(f"- **Parameter:** `{finding.parameter}`")
        lines.append(f"- **Context:** {finding.context.value if finding.context else 'unknown'}")

        if finding.waf_detected.value != "none":
            waf_status = "Bypassed" if finding.waf_bypassed else "Detected"
            lines.append(f"- **WAF:** {finding.waf_detected.value} ({waf_status})")

        lines.append("")
        lines.append("#### Payload")
        lines.append("")
        lines.append("```html")
        lines.append(finding.payload)
        lines.append("```")
        lines.append("")

        if finding.evidence:
            lines.append("#### Evidence")
            lines.append("")
            lines.append("```")
            # Truncate long evidence
            evidence = finding.evidence[:500]
            if len(finding.evidence) > 500:
                evidence += "..."
            lines.append(evidence)
            lines.append("```")
            lines.append("")

        lines.append("#### Remediation")
        lines.append("")
        lines.append(f"> {finding.remediation}")

        return lines

    def _severity_emoji(self, severity: str) -> str:
        """Get emoji for severity level."""
        emojis = {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🔵",
            "info": "⚪",
        }
        return emojis.get(severity.lower(), "⚪")

    def _type_emoji(self, xss_type: str) -> str:
        """Get emoji for XSS type."""
        emojis = {
            "reflected": "🔄",
            "stored": "💾",
            "dom": "🌐",
        }
        return emojis.get(xss_type.lower(), "❓")

    def save(self, filepath: str | Path):
        """Save report to file."""
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)

        with open(filepath, "w") as f:
            f.write(self.generate())


def generate_markdown_report(
    findings: list[XSSFinding],
    target: str = "",
    scan_time: float = 0.0,
) -> str:
    """Convenience function to generate Markdown report."""
    reporter = MarkdownReporter(findings)
    reporter.set_metadata(target=target, scan_time=scan_time)
    return reporter.generate()
